trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define the base version here, you can change it manually as needed
  baseVersion: '1.0.2'
  version: '$(baseVersion)-$(Build.BuildId)'  # Combine base version with build ID for unique versioning

stages:
- stage: Build_Stage
  displayName: Build Stage
  
  jobs:
  - job: BuildNuget
    displayName: Build NuGet Packages
    variables:
      BuildConfiguration: release
    steps:

    - task: DotNetCoreCLI@2
      displayName: Restore Packages
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build Apps
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - script: printenv

    - task: DotNetCoreCLI@2
      displayName: Pack NuGet Package
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'version'  # Use the version variable defined above
        includeSymbols: true  # Optional: Include symbols for debugging
        includeSource: true    # Optional: Include source code

  
    - task: DotNetCoreCLI@2

      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '2c1c8360-5dc0-4abf-84f5-33b1851b9f69/f0a09130-bab4-409d-bc2d-4b9b536f2459'
        arguments: '--skip-duplicate'
